name: Cypress tests
on: 
  issues:
    types: opened
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/CarTest.cy.js
