name: Cypress Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://qauto.forstudy.space/
      HTTP_USERNAME: guest
      HTTP_PASSWORD: welcome2auto

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run